[package]
name = "websvc"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.12.1"
csv = "1.4.0"
env_logger = "0.11.8"
serde = "1.0.228"
tokio = { version = "1.40.0", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
